name: lumbung_wallet_cai
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

# https://console.cloud.google.com/apis/credentials/oauthclient/439332822960-9bmur7hf5sismq6saqu3ela3cfcnfsfn.apps.googleusercontent.com?project=lumbungalgo
# flutter run -d chrome --web-hostname localhost --web-port 5000

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  repository:
    path: ../repository

  lumbung_localizations:
    path: ../../lumbung_localizations
    # git: git@bitbucket.org:enoram/lumbung_localizations.git

  core_cai_v3:
    path: ../../core-cai-v3/core_cai_v3


  cupertino_icons: ^1.0.2
  awesome_dialog: ^2.1.1
  cached_network_image: ^3.1.0+1
  fade_shimmer: ^2.0.1
  get_it: ^7.2.0
  image_picker: ^0.8.4+10
  ndialog: ^4.1.0
  go_router: ^4.3.0
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lang/en.json
    - assets/lang/id.json
    - assets/logo/
    - assets/lottie/