name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lumbung_common:
    path: ../../core-lumbung-common-2/core

  lumbung_localizations:
    path: ../../lumbung_localizations

  flutter_bloc: ^7.3.1
  get_it: ^7.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  google_fonts: ^2.1.0
  image_compression: ^1.0.3
  image_compression_flutter: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
